### ISSUE TITLE
My Mac runs OS X 10.10.5, which is lower than WebShell’s minimum deployment target. Change your project’s minimum deployment target or upgrade My Mac’s version of OS X.

### ISSUE THREAD

**Issue by neatlife** [djyde/WebShell#10]
Anyone know how to solve this problem?

**Comment by djyde** [comment]
This is a known issue. I will change the target later. Or you can manually change it in 
![image](https://cloud.githubusercontent.com/assets/914329/11948717/01b4c1f0-a8b2-11e5-844a-7b0180925e8f.png)

**Comment by neatlife** [comment]
@djyde  Thanks for your remind.

**Comment by djyde** [comment]
fixed at https://github.com/djyde/WebShell/commit/f3fb329c15d2d3573d10e632512fd81e6b33a292
