### ISSUE TITLE
Any plan to develop one for windows platform?

### ISSUE THREAD

**Issue by neatlife** [djyde/WebShell#11]

**Comment by djyde** [comment]
Windows did not come with an application build tool. And many language(framework)  can build a Windows application.

It not the same as OS X, everyone who is using OS X had an Xcode. We didn't need to care about what IDE we use or what language we use. I hope `WebShell` is an out-of-the-box stuff - clone it, and run.

But it is still worth to try. If you make a WebShell for Windows, let me know!
