### ISSUE TITLE
Webshell for iOS 

### ISSUE THREAD

**Issue by 0xWDG** [djyde/WebShell#14]
Maybe it's good to also make a iOS version.

With the local notifications and maybe some other enhancements.

**Comment by djyde** [comment]
I think ios' web app capable is enough to do this.

**Comment by 0xWDG** [comment]
If you see this: https://whatwebcando.today
There are plenty of features what can be implemented to a possible iOS version like "full screen", "notifications", "vibrations", "battery status"

**Comment by metrue** [comment]
@wdg 

I have same thought too,

Maybe we can setup a experimental project to do that.

**Comment by onato** [comment]
I just released https://github.com/intellum/neeman. It is mostly about implementing native iOS navigation for a web app. At Intellum we use it to turn our web apps into native apps that feel native. 

Let me know what you think.

**Comment by metrue** [comment]
@onato great work.

I also setup a experimental project also https://github.com/metrue/Applize .

will yours and update you if I got something to add/query.

**Comment by onato** [comment]
Thanks @metrue.

As opposed to WebShell, I will not be focusing on getting people up and running **without coding**. Perhaps there is room of a WebShell-iOS project that uses Neeman?

I have a more low level goal: use more web technologies without getting in the way of me implementing native features too much.

**Comment by metrue** [comment]
@onato 

oh, I see. Great idea.

**Comment by wdg** [comment]
@djyde Can you make a target in the Xcode project, for some strange reason if i add a target i can't compile anymore! (thanks!)

**Comment by 0xWDG** [comment]
Locked this conversation.
Deleted messages about discussing this issue.

**Comment by 0xWDG** [comment]
Status update: **Wontfix**.
The support for the OS X app has major priority.

In a later moment, I will take a look about implementing some HTML5 features in the iOS version, but the problem is we can't just reuse code.
