### ISSUE TITLE
Media key support

### ISSUE THREAD

**Issue by djyde** [djyde/WebShell#15]
Considering support media key(previous, next, play/pause)

**Comment by 0xWDG** [comment]
I don't know exactly how you want to use it, but it is supported see: https://github.com/djyde/WebShell/blob/master/WebShell/WebShellMediaKeysSupport.swift#L20

**Comment by djyde** [comment]
Actually, what i want is explosing an event listener API which let WebShell can tell the website what media key  the user press. It is a very useful feature for the video web application.

**Comment by 0xWDG** [comment]
I got (for now)

```
        "MediaKeys": [
                    // Enable "Back" & "Forward" (for browsing)
                    "BackAndForward": true,

                    // Media Player support (experimental)
                    "MediaPlayers": false
                ],
```

i'll make a event trigger API later.

---

the thing what makes the media keys support hard, is that via the media keys interface we can't communicate directly to the view controller unfortunately.

https://github.com/djyde/WebShell/blob/master/WebShell/WebShellMediaKeysSupport.swift
