### ISSUE TITLE
Broken on Google Docs/Sheets Dashboard

### ISSUE THREAD

**Issue by robgraeber** [djyde/WebShell#20]
This seems to be the same issue that Fluid has, if you set the homepage to https://docs.google.com/spreadsheets/u/0/, it will have the spinner loading forever.

![screen shot 2015-12-25 at 1 35 25 am](https://cloud.githubusercontent.com/assets/2387719/12001924/e4abee92-aaa7-11e5-9468-699433fa7ba6.png)

**Comment by djyde** [comment]
I had a try and feel very strange because I used debugger listened all the network and javascript evaluation. But there were NO any error and NO network was blocked.

![image](https://cloud.githubusercontent.com/assets/914329/12001989/5eda4b00-ab2f-11e5-9e7c-6bb6c3ac90ad.png)

**Comment by djyde** [comment]
After some researching I thought I'd knew what's wrong. Give me a few minutes.

http://stackoverflow.com/questions/15981431/showing-document-from-google-docs-in-a-webview

**Comment by 0xWDG** [comment]
The problem is something with the iframe. i will open a general iframe problem for it, handling frames has multiple problems.

**Comment by 0xWDG** [comment]
@djyde Safari analyse

Uses 2 frames wich never stop loading.
`postmessageRelay` and `frame` 

`frame` Analyse (this one contains the spinner ![Spinner](https://ssl.gstatic.com/s2/oz/images/notifications/spinner_64_b6a3129c3429eba076483f2c93ba38f6.gif))
Scheme: https
Host: plus.google.com
Path: /u/0/_/notifications/frame

`postmessageRelay` Analyse
Scheme: https
Host: accounts.google.com
Path: /o/oauth2/postmessageRelay

So i think the problem must be somewhere in `frame`
Frame loads:
- (JavaScript) https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.0qt5d8yawpg.O/m=iframes,googleapis_client/am=AAQ/rt=j/d=1/rs=AItRSTPlCaUSPAbLD881PE1fL-khxRsvgg
- (Spinner Image) https://ssl.gstatic.com/s2/oz/images/notifications/spinner_64_b6a3129c3429eba076483f2c93ba38f6.gif
- (CSS) https://plus.google.com/_/scs/apps-static/_/ss/k=oz.sbw_bss.3prwt08w3lvy.L.W.O/d=0/rs=AGLTcCPZgCmDwAIq0VhYl7SMx8oypKXi0g

Frame content [see this gist](https://gist.github.com/wdg/8dcdbcc44aa53480ec54) (some to large to post in this topic)

But when loaded separately from the google docs, you'll only see a [Loading Screen](https://www.dropbox.com/s/ezuy2qpxpw631p1/googledocs.png?dl=0)

**Comment by 0xWDG** [comment]
<img width="1112" alt="screen shot 2016-03-10 at 22 24 43" src="https://cloud.githubusercontent.com/assets/1290461/13684808/b2c270e8-e70d-11e5-8113-58ba7f07cba8.png">

Please retry yourself.

**Comment by 0xWDG** [comment]
If there is any issue, then reopen this issue, or create a new one.
i've tested it, and it passes the test.
