### ISSUE TITLE
Custom Userscripts + Userstyles?

### ISSUE THREAD

**Issue by ankushg** [djyde/WebShell#36]
Fluid supports custom Userscripts and Userstyles. Is it possible to add support for these into Webshell?

**Comment by 0xWDG** [comment]
Can you specify in what context you want it,
- Inject into Websites
- Customize the appearance of WebShell

**Comment by djyde** [comment]
@wdg Do you want to provide custom js and css?

**Comment by 0xWDG** [comment]
I think that if we support custom css/JavaScript (as a injection) would be useful in some cases.

I'm currently not thinking to change the appearance of WebShell via CSS/JavaScript

**Comment by djyde** [comment]
@wdg We can support it on `v0.2.0` if necessary.

**Comment by 0xWDG** [comment]
Fixing #53 first, then i'll release this fix.

**Comment by djyde** [comment]
@wdg Please write a reference in wiki for how to inject custom css and Javascript :)

**Comment by 0xWDG** [comment]
I will do this with the release of 0.2.0 with all functions and examples.
