### ISSUE TITLE
Loading Animation (instead of just text)

### ISSUE THREAD

**Issue by ankushg** [djyde/WebShell#37]
Would be a nice way to add some polish to slower-loading webapps :smile:

**Comment by djyde** [comment]
Will be

**Comment by djyde** [comment]
@wdg You could post a screenshot of the new loading screen

**Comment by 0xWDG** [comment]
On the first load, you will see the message "Launching..." and a progress bar 

<img width="1112" alt="screen shot 2016-02-02 at 21 25 55" src="https://cloud.githubusercontent.com/assets/1290461/12763054/acf6cd68-c9f2-11e5-8895-adf2848c26c4.png">

After the initial load, you will see the progress bar, on page change (while loading).
And of course disappear if the loading is finished.
