### ISSUE TITLE
Quit app when window is closed

### ISSUE THREAD

**Issue by schuettla** [djyde/WebShell#40]
An app I built with Webshell just got rejected from the app store with the following statement regarding the default behavior when the main window gets closed:

> We have found that when the user closes the main application window there is no menu item to 
> re-open it. The app should implement a Window menu that lists the main window so it can be 
> reopened, or provide similar functionality in another menu item. OS X Human Interface Guidelines, 
> state that "The menu bar [a]lways contains [a] Window menu".
> 
> Alternatively, if the application is a single-window app, it might be appropriate to save data and quit the > app when the main window is closed. ''

As it is an single-window app it would be good to add the behavior as stated in the HIGuidlines.

**Comment by djyde** [comment]
Feeling sorry for my ignoring.

But there is a `Window` item on menubar. Which version did you use?

![image](https://cloud.githubusercontent.com/assets/914329/12498693/71ba2dce-c0df-11e5-9c72-78031daea2da.png)

**Comment by schuettla** [comment]
I am using the master branch.
Yes, there is the Window menu but the behavior is not HIG compliant. There are 2 options:
1) When you close the main window the window menu provides a functionality to reopen the main window again. 
2) When you close the main window the whole application closes.

**Comment by 0xWDG** [comment]
```
override func viewDidDisappear() {
    exit(0);
}
```

is that a good option (uses option 2)

**Comment by 0xWDG** [comment]
Never mind. fix is there
