### ISSUE TITLE
move js hooks into separate js files

### ISSUE THREAD

**Issue by velocityzen** [djyde/WebShell#42]
Also it can be a folder, `jshooks` for example, to inject all *.js to a webview from.

**Comment by 0xWDG** [comment]
Sorry, but I don't think that is an enhancement, that only makes the injecting and the interaction more difficult than needed.

In a while we'll support custom JavaScript, and maybe custom css. (See #36 )

**Comment by 0xWDG** [comment]
It is a folder now.

If you open the app and make a folder in `Contents/Resources` called `JavaScript` 
(so: `WebShell.app/Contents/Resources/JavaScript`)
and put there the JavaScript files WebShell will load it

If you open the app and make a folder in `Contents/Resources` called `CSS`
(so: `WebShell.app/Contents/Resources/CSS`)
and put there the CSS files WebShell will load it
