### ISSUE TITLE
Trackpad gestures?

### ISSUE THREAD

**Issue by swrobel** [djyde/WebShell#44]
Back/forward with gestures doesn't seem to work. The keyboard shortcuts seem to work fine.

**Comment by 0xWDG** [comment]
@djyde do you know how those gestures works, gestures are not my best point.

**Comment by 0xWDG** [comment]
See: https://github.com/djyde/WebShell/blob/master/WebShell/WebShellTrackpadGestures.swift#l24

For some strange reason the `swipeWithEvent` is not called.

--- Please see:
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/EventOverview/HandlingTouchEvents/HandlingTouchEvents.html

**Comment by swrobel** [comment]
Maybe something useful here? https://github.com/kfix/MacPin/search?utf8=✓&q=gesture&type=Code

Gestures work on MacPin

**Comment by 0xWDG** [comment]
Good idea i Will check it later today! (In About 2 Hours)

**Comment by 0xWDG** [comment]
The only thing is that UIGesture... Only works on iOS

**Comment by swrobel** [comment]
I could be searching for the wrong thing - I don't know Mac development

**Comment by 0xWDG** [comment]
```
Moved::: NSEvent: type=Gesture loc=(554.609,-128.766) time=61269.5 flags=0x100 win=0x6100001e0200 winNum=4955 ctxt=0x0 subtype=0
DeltaY = 0.0
Swiped Unknown direction!
```

Some Progress!!!

**Comment by swrobel** [comment]
:clap:
