### ISSUE TITLE
file upload disable fakepath

### ISSUE THREAD

**Issue by defims** [djyde/WebShell#46]
will be possible disable fakepath when upload file? current webkit implement [html5's fakepath](HTML5's fakepath) because of security, but native app should handle it with nodejs or others, so disable this feature will be nice when develop native app.

**Comment by 0xWDG** [comment]
<img width="1112" alt="screen shot 2016-03-10 at 22 17 56" src="https://cloud.githubusercontent.com/assets/1290461/13684595/c2144a86-e70c-11e5-85bd-032bb0ec756a.png">

This is a built-in security feature, i don't think it's good to remove it.
you can upload to node.js it all is local, it don't cost any data and takes almost no time to handle a upload.

See file uploads for node.js: https://codeforgeek.com/2014/11/file-uploads-using-node-js/

**Comment by defims** [comment]
nodejs is nice for uploading file, what i need is the file's fullpath, webshell send the full path to nodejs, and nodejs setup a server of the path.

**Comment by 0xWDG** [comment]
What are you trying to do.
For a normal upload c:\fakepath\file.x doesn't matter.
You can easily remove it with JavaScript...

And it still has no effect on the uploading process.

See also my example if you use input field "name" instead of input field "value" you don't get c:\fakepath

Otherwise make a snippet or something to show what you're trying. Uploading works fine, local and external.

**Comment by defims** [comment]
what i want like [this](https://github.com/MacGapProject/MacGap1/pull/25)

**Comment by 0xWDG** [comment]
@djyde what do you think.

If we need this then we need to trigger a event  (event.result) after selecting the file, and make some more changes.

Please note, the c:\fakepath\ was introduced for security and now you can see the file system tree (where the file is)
- file uploading works; issue= if a file is given to the `input type="file"` then get the local file path.

**Comment by djyde** [comment]
I think WebShell is a browser, not a runtime. This problem should not be solve by WebShell.

**Comment by 0xWDG** [comment]
we have no plans to support this.
maybe in the future, more as a service then a must.

if you think it must be added to WebShell, and you can code yourself then the best solution is to create a pull request.

at least, for now, i close this issue because it has no addition for now.
