### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by kripsbro** [djyde/WebShell#49]
Can you made Notification API to work on iOS ?

**Comment by djyde** [comment]
Do you mean WebShell for iOS?

**Comment by kripsbro** [comment]
Yes, but only think i need it's Notification API :) , on OS-X works very great, i was tried to port it on iOS but it wont work :( can you help me ?

**Comment by 0xWDG** [comment]
Please see #14 

It will come, first we need to destroy some bugs on the Mac version.

**Comment by kripsbro** [comment]
ok thanks
