### ISSUE TITLE
Can't open links in browser

### ISSUE THREAD

**Issue by visoar** [djyde/WebShell#5]
Links in WebShell can't be opened when I click it.

**Comment by djyde** [comment]
It a `target="_blank"` link?

**Comment by visoar** [comment]
Yes.
And it can't be open in WebShell or system default browser.

**Comment by djyde** [comment]
It should be open in system default browser. Could you help me fix it?

**Comment by visoar** [comment]
sorry but I can't write Swift.
this link in stackoverflow may help you .
http://stackoverflow.com/questions/4530590/opening-webview-links-in-safari

**Comment by 0xWDG** [comment]
Maybe we can arrange that with a javascript bridge.
I will look at it if the current pull request is done.
