### ISSUE TITLE
add support for custom user agents 

### ISSUE THREAD

**Issue by 0xWDG** [djyde/WebShell#52]

**Comment by djyde** [comment]
Remember to release new version and new tag :)

**Comment by 0xWDG** [comment]
i'll remember it. first we'll need to kill some bugs... #47 and #36 
But i do not know how (hard) it is to build in #15 and #44 
And #31 needs also to be resolved, i think the most important ones are:
 #31 (file download)
 #47 (injecting is (sometimes) too slow)
