### ISSUE TITLE
gmail loads in basic HTML mode

### ISSUE THREAD

**Issue by spnkr** [djyde/WebShell#85]
![image](https://user-images.githubusercontent.com/11250/41346184-cd47b806-6ed3-11e8-93d0-85b367d09d6e.png)

**Comment by 0xWDG** [comment]
Try to set the user agent to Chrome or Safari, something like `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A `

**Comment by 0xWDG** [comment]
This seems to be an issue by gmail itself, it doesn't trow any errors.
And while loading I cannot find anything what doesn't work as expected.
