### ISSUE TITLE
add https to the quickstart on the cloning instruction

### ISSUE THREAD

**Issue by jajajaime** [djyde/WebShell#9]
I was getting 

```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

without the https on `git clone github.com/djyde/WebShell.git APP_NAME`

**Comment by djyde** [comment]
Oh, you may not configure your git. Use `git clone https://github.com/djyde/WebShell.git APP_NAME` instead and I will add it to  quickstart instruction later :)

**Comment by jajajaime** [comment]
Awesome! That's what I did.
